export type ValidPrismaTable =
  | "nationalities"
  | "honors"
  | "privileges"
  | "users"
  | "customers"
  | "vehicles"
  | "categories"
  | "groups"
  | "states"
  | "cities"
  | "units"
  | "reserves"
  | "status_users"
  | "status_customers";
