export type ValidPrismaTable =
  | "nationality"
  | "honor"
  | "privilege"
  | "user"
  | "customer"
  | "vehicle"
  | "category"
  | "group"
  | "state"
  | "city"
  | "unit"
  | "reserve"
  | "statusUser"
  | "statusCustomer";
